server:
  ssl:
    enabled: false
  port: 8443
  error:
    include-message: always
  reactive:
    session:
      timeout: 30d
      cookie:
        name: SESSION
        secure: false
        max-age: 30d
        http-only: true
        same-site: lax
  forward-headers-strategy: framework
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/zumely?authSource=admin
      database: zumely
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-methods: GET, POST, PUT, DELETE, OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            allowed-origin-patterns: "https://*.zumely.io"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: zumely-gateway
          uri: http://localhost:8443
          predicates:
            - Path=/api/prompt/**
  application:
    name: zumely-gateway
security:
  openai:
    secret: ${GATEWAY_SECURITY_OPENAI_SECRET}
  anonymous:
    jwt:
      secret: ${GATEWAY_SECURITY_ANONYMOUS_JWT_SECRET}
