server:
  ssl:
    enabled: false
  port: 8443
  error:
    include-message: always
  reactive:
    session:
      timeout: 30d
      cookie:
        name: SESSION
        secure: false
        max-age: 30d
        http-only: true
        same-site: lax
  forward-headers-strategy: framework
spring:
  ai:
    chat:
      observations:
        log-prompt: true
        log-completion: true
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 1536 #or 3072 for text-embedding-3-large
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: jobbortunity-gateway
              uri: http://localhost:8443
              predicates:
                - Path=/api/command/**
                - Path=/api/chats/**
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
  application:
    name: jobbortunity-gateway
gateway:
  security:
    anonymous:
      jwt:
        secret: ${GATEWAY_SECURITY_ANONYMOUS_JWT_SECRET}
