server:
  ssl:
    enabled: false
  port: 8443
  error:
    include-message: always
  reactive:
    session:
      timeout: 30d
      cookie:
        name: SESSION
        secure: false
        max-age: 30d
        http-only: true
        same-site: lax
  forward-headers-strategy: framework
spring:
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-nano
          temperature: 0.8
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: zumely-gateway
              uri: http://localhost:8443
              predicates:
                - Path=/api/command/**
                - Path=/api/chats/**
  rsocket:
    server:
      transport: websocket
      mapping-path: /api/rsocket
  application:
    name: zumely-gateway
gateway:
  security:
    anonymous:
      jwt:
        secret: ${GATEWAY_SECURITY_ANONYMOUS_JWT_SECRET}