server:
  ssl:
    enabled: false
  port: 8443
  error:
    include-message: always
  reactive:
    session:
      timeout: 30d
      cookie:
        name: SESSION
        secure: false
        max-age: 30d
        http-only: true
        same-site: lax
  forward-headers-strategy: framework
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/zumely?authSource=admin
      database: zumely
  kafka:
    bootstrap-servers: ${GATEWAY_SPRING_KAFKA_BOOTSTRAP_SERVERS}
  cloud:
    stream:
      bindings:
        handleActorEvent-in-0:
          destination: actor.events
          group: gateway
          consumer:
            # max-attempts: 3 # Example: retry configuration
            # back-off-initial-interval: 1000
            # back-off-max-interval: 10000
            # back-off-multiplier: 2.0
            concurrency: 1 # Adjust based on expected load and processing time
    function:
      definition: >
        handleActorEvent;
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-methods: GET, POST, PUT, DELETE, OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            allowed-origin-patterns: "https://*.zumely.io"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: zumely-gateway
          uri: http://localhost:8443
          predicates:
            - Path=/api/prompt/**
  application:
    name: zumely-gateway
security:
  openai:
    secret: ${GATEWAY_SECURITY_OPENAI_SECRET}
  anonymous:
    jwt:
      secret: ${GATEWAY_SECURITY_ANONYMOUS_JWT_SECRET}
